[package]
name = "secure-integer-comparison"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threshold-secret-sharing = "0.2.2"
